### ISSUE TITLE
Broken types with namespace import/export

### ISSUE THREAD

**Issue by elado** [wessberg/rollup-plugin-ts#79]
```ts
// index.ts
import * as Foo from './foo'

export { Foo }

// foo.ts
import { Bar } from './bar'

export interface Foo {
  a: number
  bar: Bar
}

// bar.ts
export interface Bar {
  b: number;
}
```

output:

```ts
declare namespace Foo {
    interface Bar {
        b: number;
    }
    import {} from "bar";
    interface Foo {
        a: number;
        bar: Bar;
    }
}
export { Foo };
```

**Comment by wessberg** [comment]
Hey there! Based on what I'm seeing here, the only thing about this that should be left out is the `import {} from "bar";` which doesn't break anything, but is unnecessary. Beside that, what I'm looking at here looks good to me. You're importing the entire namespace from `"./foo"` and then re-export it. The output inlines the namespace declaration and then exports it. What am I missing here?

**Comment by elado** [comment]
Somehow I submitted it without all the details, sorry!

the `import {} from "bar";` is indeed the issue.

it shows an error that makes the types invalid:

```
Import declarations in a namespace cannot reference a module.(1147)
```

**Comment by wessberg** [comment]
Ah, right! Thanks for the updated information. That makes sense. The issue was fixed in v1.2.17, so I'll close the issue. Thanks for reporting it!

**Comment by elado** [comment]
Thanks!
Is there be a case where the import actually imports something (and not empty `{}`)? In that case, why would it treat it as `"bar"` (absolute) and not `"./bar"` (relative)?

**Comment by wessberg** [comment]
Yes, and it has to do with the internals of how the plug-in actually brings together multiple modules and online's them within the same chunk. The imports will end up binding-less, so long as they reference symbols that isn't external to the chunk.

The absolute module specifiers has to do with how TypeScript emits modules when in a special `outFile` mode that `rollup-plugin-ts` is leveraging. In that mode, all module specifiers are absolute.

**Comment by rondonjon** [comment]
Please re-open.

I am still getting this error using version 1.3.5 of the plugin.

The generated `_bundle.d.ts` file references the external type `Big` with a similar `import`:

```
/// <reference types="big.js" />
/// <reference types="node" />
...
declare namespace X {
...
        namespace Y {
            import Big from "big.js";
            const parseNumber: (a: string) => Big | undefined;
            ...
        }
```

Output from `typedoc` while processing this file:

```
Using TypeScript 4.0.3 from /.../node_modules/typescript/lib
Error: /.../output/_bundle.d.ts(26)
 Import declarations in a namespace cannot reference a module.
Error: /.../output/_bundle.d.ts(26)
 Cannot find module 'big.js' or its corresponding type declarations.
Error: /.../output/_bundle.d.ts(44)
 'Big' refers to a value, but is being used as a type here. Did you mean 'typeof Big'?
Error: /.../output/_bundle.d.ts(109)
 'Big' refers to a value, but is being used as a type here. Did you mean 'typeof Big'?
Error: /.../output/_bundle.d.ts(110)
 'Big' refers to a value, but is being used as a type here. Did you mean 'typeof Big'?
Error: /.../output/_bundle.d.ts(111)
 'Big' refers to a value, but is being used as a type here. Did you mean 'typeof Big'?
```
